main/urls.py
from django.urls import path

from main import views

urlpatterns = [
    path('', views.CategoryListView.as_view(), name='index'),
    path('case/<int:pk>', views.CaseDetailView.as_view(), name='open-case'),
    path('open_case/<int:pk>', views.open_case),
    path('profile', views.my_profile, name='my-profile'),
    path('profile/<int:pk>', views.UserProfile.as_view(), name='profile'),
    path('send/<int:item>', views.send_item),
    path('sell/<int:item>', views.sell_item),
    path('link', views.save_link)
]

authentication/models.py
from datetime import datetime
from math import ceil

from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
from django.contrib.auth.models import PermissionsMixin
from django.db import models
from django.utils import timezone
from django.utils.translation import ugettext_lazy as _

from main.models import Item, Case


class SteamUserManager(BaseUserManager):
    def _create_user(self, steamid, password, **extra_fields):
        """
        Creates and saves a User with the given steamid and password.
        """
        try:
            # python social auth provides an empty email param, which cannot be used here
            del extra_fields['email']
        except KeyError:
            pass
        if not steamid:
            raise ValueError('The given steamid must be set')
        user = self.model(steamid=steamid, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, steamid, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(steamid, password, **extra_fields)

    def create_superuser(self, steamid, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(steamid, password, **extra_fields)


class SteamUser(AbstractBaseUser, PermissionsMixin):
    USERNAME_FIELD = 'steamid'
    DEFAULT_AFFILIATE_ID = 1
    steamid = models.CharField(max_length=17, unique=True)
    personaname = models.CharField(max_length=255)
    profileurl = models.CharField(max_length=300)
    avatar = models.CharField(max_length=255)
    avatarmedium = models.CharField(max_length=255)
    avatarfull = models.CharField(max_length=255)
    balance = models.PositiveIntegerField(default=0)
    items_won = models.ManyToManyField(Item, blank=True, through='Win')
    trade_link = models.CharField(max_length=500, blank=True, null=True)
    affiliate = models.ForeignKey('self', on_delete=models.CASCADE, blank=True, default=DEFAULT_AFFILIATE_ID)

    # Add the other fields that can be retrieved from the Web-API if required

    date_joined = models.DateTimeField(_('date joined'), default=timezone.now)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)

    objects = SteamUserManager()

    def get_short_name(self):
        return self.personaname

    def get_full_name(self):
        return self.personaname

    def __str__(self):
        return self.get_full_name()

    def days_joined(self):
        return (datetime.now(timezone.utc) - self.date_joined).days

    def money_won(self):
        return ceil(sum([item.cost for item in self.items_won.all()]))


class Win(models.Model):
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    steam_user = models.ForeignKey(SteamUser, on_delete=models.CASCADE)
    case = models.ForeignKey(Case, on_delete=models.CASCADE)
    time = models.DateTimeField(auto_now_add=True)
    state = models.PositiveSmallIntegerField(default=0)

    def get_current_state_name(self):
        states = ["Производится выбор", "Продано", "Отправлено"]
        return states[self.state]

main/models.py
from django.db import models, transaction


class BaseItem(models.Model):
    name = models.CharField(max_length=255)
    image = models.CharField(max_length=500)
    quantity = models.PositiveIntegerField()
    category = models.CharField(max_length=255)
    rarity = models.CharField(max_length=255)
    rarity_class = models.CharField(max_length=255)
    class_id = models.BigIntegerField()

    def __str__(self):
        return f"{self.name} - {self.category} - {self.rarity} - {self.quantity}шт"


class Item(models.Model):
    base = models.ForeignKey(BaseItem, on_delete=models.CASCADE)
    cost = models.FloatField()
    steam_id = models.BigIntegerField(unique=True)
    market_name = models.CharField(max_length=255)
    used = models.BooleanField(blank=True, default=False)

    def __str__(self):
        return f"{self.market_name} - {self.cost}р"


class Category(models.Model):
    name = models.CharField(max_length=255)
    exclusive = models.BooleanField()

    def __str__(self):
        return self.name


# Create your models here.
class Case(models.Model):
    name = models.CharField(max_length=255)
    base_items = models.ManyToManyField(BaseItem, through='Entry', blank=True)
    cost = models.IntegerField(default=0, blank=True)
    image = models.ImageField(upload_to="covers")
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name="cases")
    active = models.BooleanField(default=True, blank=True)

    def __str__(self):
        return f"{self.name} - {self.base_items.count()} items - {self.cost}р"

    def delete(self, using=None, keep_parents=False):
        with transaction.atomic():
            for record in self.record_set.select_for_update().all():
                record.item.used = False
                record.item.save()
                record.item.base.quantity += 1
                record.item.base.save()
        return super(Case, self).delete(using, keep_parents)


class Entry(models.Model):
    base_item = models.ForeignKey(BaseItem, on_delete=models.CASCADE)
    case = models.ForeignKey(Case, on_delete=models.CASCADE)
    num = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.base_item.__str__()


class Record(models.Model):
    case = models.ForeignKey(Case, on_delete=models.CASCADE)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)

main/views.py
import json

from django.db import transaction
from django.http import HttpResponse
from django.shortcuts import render
from django.views.generic import DetailView, ListView
from rest_framework import status
from steampy.client import SteamClient, GameOptions
from steampy.models import Asset

from authentication.models import Win, SteamUser
# Create your views here.
from main.models import Case, Item, Category
from onlinecsgo.settings import MEDIA_URL
from onlinecsgo.settings import SOCIAL_AUTH_STEAM_API_KEY


class CategoryListView(ListView):
    model = Category
    template_name = "main/index.html"
    context_object_name = 'categories'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["MEDIA_URL"] = MEDIA_URL
        context["wins"] = Win.objects.order_by("-id")[:10]
        return context


class CaseDetailView(DetailView):
    model = Case
    context_object_name = 'case'
    template_name = "main/case.html"

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data["roulette_items"] = [context_data["case"].base_items.order_by('?').first() for _ in range(150)]
        return context_data


def open_case(request, pk):
    if request.user.is_anonymous:
        return HttpResponse({'Login required': 'login with your steam account first'},
                            status=status.HTTP_403_FORBIDDEN)
    case = Case.objects.get(id=pk)
    if request.user.balance < case.cost:
        return HttpResponse({'Not enough money': 'this case is too expensive for you'},
                            status=status.HTTP_402_PAYMENT_REQUIRED)
    with transaction.atomic():
        record = case.record_set.select_for_update().first()
        item = record.item
        record.delete()
    Win.objects.create(case=case, item=item, steam_user=request.user)
    request.user.balance -= case.cost
    request.user.save()
    if case.record_set.count() == 0:
        case.active = False
        case.save()
    can_open = case.active and request.user.balance >= case.cost
    disabled_message = ""
    if not request.user.balance >= case.cost:
        disabled_message = "Пополните баланс"
    elif not case.active:
        disabled_message = "Кейс временно недоступен"
    return HttpResponse(json.dumps({
        "pk": item.pk,
        "name": item.base.name,
        "image": item.base.image,
        "rarity": item.base.rarity,
        "category": item.base.category,
        "rarity_class": item.base.rarity_class,
        "market_name": item.market_name,
        "cost": item.cost,
        "balance": request.user.balance,
        "can_open": can_open,
        "disabled_message": disabled_message
    }))


class UserProfile(DetailView):
    model = SteamUser
    context_object_name = "user"
    template_name = "main/profile-v2.html"


def my_profile(request):
    if request.user.is_anonymous:
        return HttpResponse({'Login required': 'login with your steam account first'},
                            status=status.HTTP_403_FORBIDDEN)
    return render(request, "main/profile-v2.html", context={"user": request.user, "is_myself": True})


def send_item(request, item):
    return False  # to disable for testing
    if request.user.is_anonymous:
        return HttpResponse({'Login required': 'login with your steam account first'},
                            status=status.HTTP_403_FORBIDDEN)
    steam_client = SteamClient(SOCIAL_AUTH_STEAM_API_KEY)
    steam_client.login("Eonixpharos", "Onlinecsgo123", "onlinecsgo/steam_guard.txt")
    if not request.user.trade_link:
        return HttpResponse({"Not executed": "Trade link required", },
                            status=status.HTTP_406_NOT_ACCEPTABLE)
    win = Win.objects.filter(steam_user=request.user, item=Item.objects.get(pk=item), state=0).first()
    item = win.item
    asset = Asset(item.steam_id, GameOptions.CS)
    response = steam_client.make_offer_with_url([asset], [], request.user.trade_link,
                                                "Your prize from onlinecsgo.com!")
    if "strError" not in response:
        win.state = 1
        win.save()
    else:
        return HttpResponse(json.dumps(response), status=status.HTTP_406_NOT_ACCEPTABLE)
    return HttpResponse(json.dumps(response))


def sell_item(request, item):
    if request.user.is_anonymous:
        return HttpResponse({'Login required': 'login with your steam account first'},
                            status=status.HTTP_403_FORBIDDEN)
    win = Win.objects.filter(steam_user=request.user, item=Item.objects.get(pk=item), state=0).first()
    if win is None:
        return HttpResponse(json.dumps({
            "result": "ERROR"
        }))
    request.user.balance += win.item.cost
    request.user.save()
    win.state = 2
    win.save()
    win.item.used = False
    win.item.base.quantity += 1
    win.item.base.save()
    win.item.save()
    return HttpResponse(json.dumps({"result": "OK", "balance": request.user.balance}))


def save_link(request):
    if request.user.is_anonymous:
        return HttpResponse({'Login required': 'login with your steam account first'},
                            status=status.HTTP_403_FORBIDDEN)
    request.user.trade_link = request.POST["link"]
    request.user.save()
    return HttpResponse(json.dumps({"result": "saved"}))

main/templates/main/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}CS:GO cases{% endblock %}</title>
    {#    <link href="https://cdnjs.cloudflare.com/ajax/libs/angular-toastr/2.1.1/angular-toastr.min.css" rel="stylesheet">#}
    {#    <link href="https://cdnjs.cloudflare.com/ajax/libs/spinkit/1.2.5/spinners/3-wave.min.css" rel="stylesheet">#}
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.0/css/bootstrap.min.css">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <link href="{% static 'css/fixes.css' %}" rel="stylesheet">
    <link href="{% static 'css/roulette.css' %}" rel="stylesheet">
    <link href="{% static 'css/snackbar.css' %}" rel="stylesheet">
    <link href="{% static 'css/profile.css' %}" rel="stylesheet">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.0/jquery-ui.min.js"></script>
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
    <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
    <script src="{% static 'js/snackbar.js' %}"></script>
    <script src="{% static 'js/roulette.js' %}"></script>
    <script src="{% static 'js/actions.js' %}"></script>
    <script src="{% static 'js/profile.js' %}"></script>
</head>
<body>
{% include "main/sidebar.html" %}
<div class="page">
    {% block main %}{% endblock %}
</div>
</body>
</html>

main/templates/main/case.html
{% extends "main/base.html" %}
{% block title %}{{ case.name }}{% endblock %}
{% block main %}
    <div class="page--title">
        <span>{{ case.name }}</span>
    </div>
    {% include "main/roulette.html" %}
    <div class="page--title">
        <span><i>Вероятный</i> дроп из кейса</span>
    </div>
    <div class="contracts no-bg">
        <div class="ng-scope">
            <div class="contracts--choose">
                <div class="contracts--choose-grid">
                    <center>
                        {% for item in case.base_items.all %}
                            <div class="contracts--choose-item">
                                <a class="contracts--weapon {{ item.rarity_class }}">
                                <span class="contracts--weapon-photo">
                                        <img src="{{ item.image }}">
                                </span>
                                    <span class="contracts--weapon-title">{{ item.name }}</span>
                                    <span class="contracts--weapon-type">{{ item.category }}</span>
                                </a>
                            </div>
                        {% endfor %}
                    </center>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

main/templates/main/index.html
{% extends "main/base.html" %}
{% block main %}
    {% if wins.count > 0 %}
        <div class="ng-scope">
            <div class="page--title">
                <span><i>Live</i></span>
            </div>
            <div class="live">
                {% for win in wins %}
                    <div class="live--item">
                        <div class="live--photo">
                            <img src="{{ win.item.base.image }}">
                        </div>
                        <a class="live--avatar"
                           style="background-image: url({{ win.steam_user.avatarmedium }});"
                           href="/profile/{{ win.steam_user.id }}"></a>
                        <a class="live--title ng-binding"
                           href="/profile/{{ win.steam_user.id }}">{{ win.steam_user.get_full_name }}</a>
                        <div class="live--type ng-binding">{{ win.item.market_name }}</div>
                    </div>
                {% endfor %}
            </div>
        </div>
    {% endif %}
    {% for category in categories %}
        {% if category.cases.count > 0 %}
            <div class="page--title">
                <span><i>{{ category.name }}</i> кейсы</span>
            </div>
        {% endif %}
        {% if category.exclusive %}
            <div class="exclusive">
            <div class="row">
                {% for case in category.cases.all %}
                    {% if case.active %}
                        <div class="col-md-6 col-xlg-4">
                    {% else %}
                        <div class="col-md-6 col-xlg-4 case-disabled">
                    {% endif %}
                <a class="exclusive--item"
                   href="{% url 'open-case' case.id %}"
                   style="background-image: url(http://csgo-happy.ru/assets/770300ec/img/exclusive--01-b.png)"
                >
                        <span class="exclusive--photo">
                            <img src="{{ MEDIA_URL }}{{ case.image }}">
                        </span>
                    <span class="exclusive--title">{{ case.name }}</span>
                    <span class="exclusive--desc">Кейс</span>
                    <span class="exclusive--price">{{ case.cost }}₽</span>
                </a>
                </div>
                {% endfor %}
                </div>
            </div>
        {% else %}
            <div class="casegrid">
            {% for case in category.cases.all %}
                {% if case.active %}
                    <div class="casegrid--item ng-scope">
                {% else %}
                    <div class="casegrid--item ng-scope case-disabled">
                {% endif %}
            <a class="case" href="/case/{{ case.id }}">
                            <span class="case--photo">
                                <img src="{{ MEDIA_URL }}{{ case.image }}">
                            </span>
                <span class="case--name ng-binding">{{ case.name }}</span>
                <span class="case--price ng-binding ng-scope">{{ case.cost }} ₽</span>
            </a>
            </div>
            {% endfor %}
        </div>
        {% endif %}
    {% endfor %}
{% endblock %}

main/templates/main/profile-v2.html
{% extends "main/base.html" %}
{% block main %}
    <div class="ng-scope">
        {% if request.user == user %}
            <div class="page--title ng-scope"><span><i>Личный</i> кабинет</span></div>
        {% else %}
            <div class="page--title ng-scope ng-hide"><span>Профиль</span></div>
        {% endif %}
        <div class="profile-header-container">
            <div class="profile-header-img">
                <img class="img-circle"
                     src="{{ user.avatarfull }}"/>
                <div class="rank-label-container">
                    <span class="label label-default rank-label">{{ user.personaname }}</span>
                </div>
            </div>
        </div>

                <center>
       	<div class="wrapper">
            <div class="row">
                    <div class="counter col_third">
                        <i class="fa fa-code fa-2x"></i>
                        <h2 class="timer count-title count-number" data-to="{{ user.items_won.count }}"
                            data-speed="1500"></h2>
                        <p class="count-text ">Кейсов открыто</p>
                    </div>
                    <div class="counter col_third">
                        <i class="fa fa-coffee fa-2x"></i>
                        <h2 class="timer count-title count-number" data-to="{{ user.days_joined }}" data-speed="1500">
                            +</h2>
                        <p class="count-text ">Дней с нами</p>
                    </div>
                    <div class="counter col_third end">
                        <i class="fa fa-coffee fa-2x"></i>
                        <h2 class="timer count-title count-number" data-to="{{ user.money_won }}" data-speed="1500">
                            +</h2>
                        <p class="count-text ">Выигранно рублей</p>
                    </div>
            </div>
                    </div>

            </center>

        <div class="row">
            <center>
            {% if request.user == user %}
                <div class="col-md-6 col-xlg-4">
                    <div class="cabinet--box">
                        <div class="cabinet--title">Пополнение баланса</div>
                        <div class="cabinet--desc">После оплаты деньги автоматически поступают на ваш баланс
                        </div>
                        <div class="cabinet--code"
                             style="width: 200px;display: inline-block;vertical-align: top;">
                            <form class="ng-pristine ng-valid" action="/profile/invoice" method="POST"
                                  target="_blank">
                                <input name="sum" class="cabinet--code-l" type="text"
                                       placeholder="Введите сумму...">
                                <input name="method" type="hidden" value="card" autocomplete="off">
                                <input name="_csrf" type="hidden"
                                       value="DXugg_6VQ3E1K2aBqrCgqAVfaIJsDoNWeCj2A2cx5E96UyjFGpjDJErQP_8YReFdnO29PqIbaE_gBr72yi1s9A=="
                                       autocomplete="off">
                                <button class="cabinet--code-b" type="submit"><i class="icon-plus"></i>
                                </button>
                            </form>
                        </div>
                        <div class="cabinet--title">Удобная оплата</div>
                        <div class="cabinet--desc">Мы принимаем оплату от таких платежных систем:</div>
                        <div class="cabinet--payments"><i class="icon-p01"></i><i class="icon-p02"></i><i
                                class="icon-p03"></i><i class="icon-p04"></i><i class="icon-p05"></i><i
                                class="icon-p06"></i></div>
                    </div>
                </div>
            {% endif %}
            {% if request.user == user %}
                <div class="col-md-6 col-xlg-4" ng-show="profile.userData.isMe">
                    <div class="cabinet--box">
                        <div class="cabinet--title">Trade-URL</div>
                        <div class="cabinet--desc">Обязательно откройте инвентарь в Steam для получения
                            приза!
                        </div>
                        <div class="cabinet--code">
                            <form method="POST">
                                <input class="cabinet--code-l"
                                        {% if user.trade_link %}
                                       value="{{ user.trade_link }}"
                                        {% endif %}
                                       placeholder="Введите ссылку на обмен"
                                       name="link"
                                       type="text">
                                <button class="cabinet--code-b" type="submit"
                                        onclick="sendLink(); return false;">
                                    <i class="icon-gift"></i>
                                </button>
                            </form>
                        </div>
                        <div class="cabinet--steps">
                            <div class="cabinet--step"><span>1</span>
                                <p>Чтобы узнать вашу ссылку нужно сделать всего два действия, войти на сайте
                                    стима :</p>
                                <p><a href="#">https://steamcommunity.com/login/home/</a></p>
                            </div>
                            <div class="cabinet--step"><span>2</span>
                                <p>После входа в стим, вам нужно перейти по этой ссылке :</p>
                                <p>
                                    <a href="#">http://steamcommunity.com/id/me/tradeoffers/privacy#trade_offer_access_url</a>
                                </p>
                                <p>Внизу вы найдете вашу ссылку на обмен. Далее просто скопируйте ее и
                                    введите в
                                    окно
                                    покупки.</p>
                            </div>
                        </div>
                    </div>
                </div>
            {% endif %}
                </center>
        </div>
        {% if user.items_won.count > 0 %}
            {% if request.user == user %}
                <div class="page--title"><span><i>Ваши</i> предметы</span></div>
            {% else %}
                <div class="page--title "><span>Предметы</span></div>
            {% endif %}
            <div class="contracts no-bg">
                <div class="row">
                    <div class="contracts--choose">
                        <div class="contracts--choose-grid">
                            <center>
                                {% for win in user.win_set.all %}
                                    <div class="contracts--choose-item">
                                        <div class="have-item--info">
                                            <div id="stateText{{ win.id }}"
                                                 class="have-item--status ng-binding">
                                                {% if win.state == 0 %}
                                                    В ожидании
                                                {% elif win.state == 1 %}
                                                    Отправлено
                                                {% elif win.state == 2 %}
                                                    Продано
                                                {% endif %}
                                            </div>
                                            <div class="have-item--id ng-binding">#{{ win.item.id }}</div>
                                        </div>
                                        <a class="contracts--weapon {{ win.item.base.rarity_class }}">
                                            <span class="contracts--weapon-photo">
                                                <img src="{{ win.item.base.image }}">
                                            </span>
                                            <span class="contracts--weapon-title">{{ win.item.base.name }}</span>
                                            <span class="contracts--weapon-type">{{ win.item.base.category }}</span>
                                        </a>
                                        {% if request.user == user and win.state == 0 %}
                                            <div id="ss{{ win.id }}" class="have-item--btns">
                                                <div class="have-item--btn">
                                                    <a href="#"
                                                       onclick="sendItem({{ win.item.id }}, {{ win.id }}); return false;">Забрать</a>
                                                </div>
                                                <div class="have-item--btn">
                                                    <a href="#"
                                                       onclick="sellItem({{ win.item.id }}, {{ win.id }}); return false;">Продать</a>
                                                </div>
                                            </div>
                                        {% endif %}
                                    </div>
                                {% endfor %}
                            </center>
                        </div>
                    </div>
                </div>
            </div>
            </div>
        {% endif %}
    </div>
{% endblock %}

main/templates/main/roulette.html
<center>
    <div id="unbox-area">
        <div id="arrow" class="arrow-down"></div>
        <div id="cardList">
            {% for item in roulette_items %}
                <div id="card{{ forloop.counter }}" class="card {{ item.rarity_class }}">
                    <img id="img{{ forloop.counter }}" src="{{ item.image }}">
                </div>
            {% endfor %}
        </div>
    </div>
</center>
{% if request.user.is_authenticated and case.active and request.user.balance >= case.cost %}
    <a id="open-button" class="contracts--start" onclick="openCase({{ case.id }}); return false;">Открыть кейс</a>
{% elif not request.user.is_authenticated %}
    <a id="open-button" class="contracts--start" href="{% url "social:begin" "steam" %}">Авторизируйтесь</a>
{% elif not case.active %}
    <a id="open-button" class="contracts--start case-disabled">Кейс временно недоступен</a>
{% else %}
    <a id="open-button" class="contracts--start">Пополните баланс</a>
{% endif %}
<div id="result_modal" class="modals modals-shown" style="display: none">
    <div class="modals--overlay">
    </div>
    <div class="modals--item is-result modals-shown" id="mResult">
        <div class="m-result">
            <a class="m-support--close" href="#" onclick="$('#result_modal').hide(); return false;">
                <i class="icon-close"></i>
            </a>

            <div id="result_title" class="m-result--title"></div>
            <div id="result_type" class="m-result--type is-c1"></div>
            <div id="result_price" class="m-result--price"></div>
            <div id="result_circle" class="m-result--circle is-c1"></div>
            <div class="m-result--photo">
                <img id="prize_image" src="#">
            </div>
            <div class="m-result--btns">
                <a class="m-result--btn is-inverse" id="sendButton">Забрать</a>
                <a class="m-result--btn is-inverse" id="sellButton">Продать</a>
            </div>
        </div>
    </div>
</div>